--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Debian 15.8-0+deb12u1)
-- Dumped by pg_dump version 15.8 (Debian 15.8-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: structure; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.structure (
    id integer NOT NULL,
    module integer,
    template text,
    url text,
    name text,
    active boolean
);


ALTER TABLE public.structure OWNER TO root;

--
-- Name: find_unique_url(text); Type: FUNCTION; Schema: public; Owner: root
--

CREATE FUNCTION public.find_unique_url(text) RETURNS SETOF public.structure
    LANGUAGE plpgsql
    AS $_$
BEGIN
    RETURN QUERY SELECT * FROM structure WHERE url = $1 LIMIT 1;
END;
$_$;


ALTER FUNCTION public.find_unique_url(text) OWNER TO root;

--
-- Name: modules; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.modules (
    id integer NOT NULL,
    name text,
    type text,
    controller_name text
);


ALTER TABLE public.modules OWNER TO root;

--
-- Name: get_module_by_id(text); Type: FUNCTION; Schema: public; Owner: root
--

CREATE FUNCTION public.get_module_by_id(text) RETURNS SETOF public.modules
    LANGUAGE plpgsql
    AS $_$
BEGIN
    RETURN QUERY SELECT * FROM modules WHERE id = $1 LIMIT 1;
END;
$_$;


ALTER FUNCTION public.get_module_by_id(text) OWNER TO root;

--
-- Name: modules_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.news (
    id integer NOT NULL,
    node_id integer,
    title_small text,
    author text,
    url text,
    text text,
    textsmall text,
    datecreated date,
    photo_name text,
    photo_title text,
    sort integer,
    active integer,
    visits integer
);


ALTER TABLE public.news OWNER TO root;

--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.products (
    id integer NOT NULL,
    model character varying(30) NOT NULL,
    company character varying(30) NOT NULL,
    price integer NOT NULL
);


ALTER TABLE public.products OWNER TO root;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: table_name_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.structure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.table_name_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login text,
    password text,
    email text,
    salt text
);


ALTER TABLE public.users OWNER TO root;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: modules; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.modules (id, name, type, controller_name) FROM stdin;
1	Новости	news	news
\.


--
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.news (id, node_id, title_small, author, url, text, textsmall, datecreated, photo_name, photo_title, sort, active, visits) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.products (id, model, company, price) FROM stdin;
4	iPhone X	Apple	72000
5	iPhone X	Apple	72000
7	iPhone X	Apple	72000
8	iPhone X	Apple	72000
9	iPhone X	Apple	72000
10	iPhone X	Apple	72000
11	iPhone X	Apple	72000
12	iPhone X	Apple	72000
13	iPhone X	Apple	72000
14	iPhone X	Apple	72000
15	iPhone X	Apple	72000
16	iPhone X	Apple	72000
17	iPhone X	Apple	72000
18	iPhone X	Apple	72000
19	iPhone X	Apple	72000
20	iPhone X	Apple	72000
21	iPhone X	Apple	72000
22	iPhone X	Apple	72000
23	iPhone X	Apple	72000
24	iPhone X	Apple	72000
2	iPhone X	Apple	123
1	iPhone X	Apple	123
3	iPhone X	Apple	12312
6	iPhone X	Apple1	72000
\.


--
-- Data for Name: structure; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.structure (id, module, template, url, name, active) FROM stdin;
1	1	index.tmp	index1	главная	t
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.users (id, login, password, email, salt) FROM stdin;
1	admin	$2a$10$ri4gx80pdX54HnvfnpNCxuEGHg2.19vHbzCYOruiFJAKC4mX0oqT2	larionov821@gmail.com	\N
\.


--
-- Name: modules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.modules_id_seq', 1, false);


--
-- Name: news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.news_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.products_id_seq', 24, true);


--
-- Name: table_name_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.table_name_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: users id; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT id PRIMARY KEY (id);


--
-- Name: modules modules_pk; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT modules_pk PRIMARY KEY (id);


--
-- Name: news news_pk; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pk PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: structure structure_pk; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.structure
    ADD CONSTRAINT structure_pk PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

